### ISSUE TITLE
fi letter combination in not displayed correctly in Atom macOS Sierra, Menlo font.

### ISSUE THREAD

**Issue by nashokin** [Alhadis/Menloco#1]
fi letter combination in not displayed correctly in Atom macOS Sierra, Menlo font.
![screen shot 2016-10-27 at 2 43 25 pm](https://cloud.githubusercontent.com/assets/6571738/19753841/e9f53a9a-9c53-11e6-9116-8ce096a76b36.png)

Meslo LG S, how it's personally desirable to me, maybe above is intentional...
![screen shot 2016-10-27 at 2 46 28 pm](https://cloud.githubusercontent.com/assets/6571738/19753858/1135bbd4-9c54-11e6-89f1-ff841a463287.png)

**Comment by Alhadis** [comment]
Add this to your user stylesheet:

``` less
atom-text-editor, :host{
    font-variant-ligatures: no-common-ligatures;
}
```
